# Generated by Django 3.1.1 on 2020-10-11 05:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Address')),
                ('suburb', models.TextField(verbose_name='Suburb')),
                ('city', models.TextField(verbose_name='City')),
                ('state', models.TextField(blank=True, null=True, verbose_name='State')),
                ('country', models.TextField(verbose_name='Country')),
                ('postcode', models.TextField(verbose_name='Postcode')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.TextField(verbose_name='Event Title')),
                ('location', models.TextField(verbose_name='Location')),
                ('description', models.TextField(verbose_name='Description')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('end_time', models.DateTimeField(verbose_name='End Time')),
                ('attachment', models.TextField(verbose_name='Attach File')),
            ],
        ),
        migrations.CreateModel(
            name='Greeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=255, verbose_name='Post Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('help_status', models.TextField(choices=[('Needed', 'Needs Help'), ('Not_Needed', 'Has been helped'), ('Being', 'Being helped')])),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Created Date')),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
    ]
