# Generated by Django 3.0.8 on 2020-09-16 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.TextField(verbose_name='Post Title')),
                ('location', models.TextField(verbose_name='Location')),
                ('description', models.TextField(verbose_name='Description')),
                ('help_status', models.TextField(verbose_name='Help status')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(verbose_name='Username')),
                ('first_name', models.TextField(verbose_name='FirstName')),
                ('last_name', models.TextField(verbose_name='LastName')),
                ('email', models.TextField(verbose_name='Email')),
                ('password', models.TextField(verbose_name='Password')),
            ],
        ),
        migrations.AlterField(
            model_name='greeting',
            name='when',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
    ]
