# Generated by Django 3.1.1 on 2020-10-18 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['email']},
        ),
        migrations.RemoveField(
            model_name='assisstant',
            name='helper',
        ),
        migrations.RemoveField(
            model_name='event',
            name='organiser',
        ),
        migrations.RemoveField(
            model_name='helper',
            name='helper',
        ),
        migrations.RemoveField(
            model_name='post',
            name='poster',
        ),
    ]
