# Generated by Django 3.1.1 on 2020-09-23 02:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='location',
        ),
        migrations.AddField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='help_status',
            field=models.TextField(choices=[('Needed', 'Needs Help'), ('Not_Needed', 'Has been helped'), ('Being', 'Being helped')]),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_title',
            field=models.CharField(max_length=255, verbose_name='Post Title'),
        ),
    ]
