# Generated by Django 3.1.1 on 2020-10-18 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_post_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='helper',
            name='helper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
