# Generated by Django 3.1.1 on 2020-10-05 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_auto_20200923_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Address')),
                ('suburb', models.TextField(verbose_name='Suburb')),
                ('city', models.TextField(verbose_name='City')),
                ('state', models.TextField(blank=True, null=True, verbose_name='State')),
                ('country', models.TextField(verbose_name='Country')),
                ('postcode', models.TextField(verbose_name='Postcode')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
