# Generated by Django 3.1.1 on 2020-10-06 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_auto_20201005_1954'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Addres',
            new_name='Address',
        ),
    ]
