# Generated by Django 3.1.2 on 2020-10-21 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_event_organiser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.TextField(),
        ),
    ]
