# Generated by Django 3.1.2 on 2020-10-23 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_auto_20201021_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hello.address'),
        ),
    ]
