# Generated by Django 3.1.2 on 2020-10-24 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0009_user_user_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_address',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(default='Mount Albert, Auckland, New Zealand'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
