# Generated by Django 3.1.2 on 2020-10-25 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0011_auto_20201024_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(default='Mount Albert, Auckland, New Zealand', max_length=1025),
        ),
    ]
