# Generated by Django 3.1.2 on 2020-10-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0013_auto_20201026_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=1025, verbose_name='Location'),
        ),
    ]
