# Generated by Django 3.1.2 on 2020-10-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0014_auto_20201026_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(default='Unitec Institute of Technology, Mt Albert Campus Map Carrington Road, Mount Albert, Auckland, New Zealand', max_length=2225, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(default='Mount Albert, Auckland, New Zealand', max_length=2225),
        ),
    ]
