# Generated by Django 3.1.2 on 2020-10-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0015_auto_20201026_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Attach File'),
        ),
    ]
